version: '3'

  orderservice:
    image: orderservice
    build:
      context: ./OrderService
      dockerfile: Dockerfile

  basketservice:
    image: basketservice
    build:
      context: ./../BasketService
      dockerfile: Dockerfile
